In [3]:
import numpy as np
import torch

logits = torch.tensor([[2.0, 1.0, 0.1, -1, 4]])
probs = torch.softmax(logits, dim=1)
print(probs)
probs.sum(dim=1) 

labels = [0,1,2,3,4,5,6,7,8]
pred_label_indices = np.argsort(probs)
print(pred_label_indices)
# pred_labels = labels[pred_label_indices[:,:]]



tensor([[0.1117, 0.0411, 0.0167, 0.0056, 0.8250]])
tensor([[3, 2, 1, 0, 4]])


In [4]:
import numpy as np
arr = np.array([[3, 1, 2]])
np.argsort(arr)

array([[1, 2, 0]])

In [6]:
x = torch.tensor([2.0, 1.0, 0.1])
x = np.array([2.0, 1.0, 0.1])

probs = torch.softmax(x, dim=0)
print(probs)

TypeError: softmax() received an invalid combination of arguments - got (numpy.ndarray, dim=int), but expected one of:
 * (Tensor input, int dim, torch.dtype dtype = None, *, Tensor out = None)
 * (Tensor input, name dim, *, torch.dtype dtype = None)
